DROP TABLE IF EXISTS ONLINE_CONSULTATIONS;
DROP TABLE IF EXISTS EXPLANATIONS;
DROP TABLE IF EXISTS MEDICAL_INDICATORS;
DROP TABLE IF EXISTS LAB_RESULTS;
DROP TABLE IF EXISTS PHYSICAL_ACTIVITIES;
DROP TABLE IF EXISTS MEDICATIONS;
DROP TABLE IF EXISTS DOCTORS;
DROP TABLE IF EXISTS USERS;

-- Створення таблиці Користувачів
CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    USER_NAME VARCHAR(255) NOT NULL,
    PHYSICAL_STATE VARCHAR(255)
);

-- Створення таблиці Лікарів
CREATE TABLE DOCTORS (
    ID SERIAL PRIMARY KEY,
    DOCTOR_NAME VARCHAR(255) NOT NULL,
    SPECIALIZATION VARCHAR(100)
);

-- Створення таблиці Медикаментів
CREATE TABLE MEDICATIONS (
    ID SERIAL PRIMARY KEY,
    MEDICATION_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT
);

-- Створення таблиці Фізичних активностей
CREATE TABLE PHYSICAL_ACTIVITIES (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    ACTIVITY_DATE DATE NOT NULL,
    ACTIVITY_TYPE VARCHAR(100),
    DURATION VARCHAR(50),
    CALORIES VARCHAR(50),

    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    CONSTRAINT CHK_DURATION_FORMAT CHECK (DURATION ~ '^\d+ хв$')
);

-- Створення таблиці Результатів аналізів
CREATE TABLE LAB_RESULTS (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    RESULT_DATE DATE NOT NULL,

    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

-- Створення таблиці Медичних показників
CREATE TABLE MEDICAL_INDICATORS (
    ID SERIAL PRIMARY KEY,
    LAB_RESULT_ID INTEGER NOT NULL,
    INDICATOR_NAME VARCHAR(100) NOT NULL,
    INDICATOR_VALUE VARCHAR(100) NOT NULL,

    FOREIGN KEY (LAB_RESULT_ID) REFERENCES LAB_RESULTS (ID) ON DELETE CASCADE
);

-- Створення таблиці Пояснень
CREATE TABLE EXPLANATIONS (
    ID SERIAL PRIMARY KEY,
    MEDICAL_INDICATOR_ID INTEGER NOT NULL,
    EXPLANATION_TEXT TEXT,

    FOREIGN KEY (MEDICAL_INDICATOR_ID) REFERENCES MEDICAL_INDICATORS (
        ID
    ) ON DELETE SET NULL
);

-- Створення таблиці Онлайн-консультацій
CREATE TABLE ONLINE_CONSULTATIONS (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    DOCTOR_ID INTEGER NOT NULL,
    DATE_TIME TIMESTAMP NOT NULL,
    CONSULTATION_TYPE VARCHAR(50),

    FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS (ID),
    CONSTRAINT CHK_CONSULTATION_TYPE CHECK (CONSULTATION_TYPE ~ '^(чат|відео)$')
);
